// Code generated by goctl. DO NOT EDIT.
package types

type AddCustomerReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	NickName string `json:"nickName"`
}

type AddCustomerResp struct {
	Id int64 `json:"id"`
}

type AddUserReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	NickName string `json:"nickName"`
}

type AddUserResp struct {
	Id int64 `json:"id"`
}

type DeleteCustomerReq struct {
	Id int64 `json:"id"`
}

type DeleteUserReq struct {
	Id int64 `json:"id"`
}

type ListCustomerData struct {
	Id       int64  `json:"id"`
	UserName string `json:"user_name"`
	Platform int    `json:"-" gorm:"-"`
}

type ListCustomerReq struct {
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
	UserName string `form:"user_name,optional"`
}

type ListCustomerResp struct {
	PageInfo
	List []ListCustomerData `json:"list"`
}

type PageInfo struct {
	Current  int   `json:"current"`
	PageSize int   `json:"page_size"`
	Total    int64 `json:"total"`
}

type QueryCustomerReq struct {
	Id int64 `path:"id"`
}

type QueryCustomerResp struct {
	Id         int64  `json:"id"`
	Account    string `json:"account"`
	NickName   string `json:"nickName"`
	CreateTime string `json:"createTime"`
}

type QueryUserReq struct {
	Id int64 `path:"id"`
}

type QueryUserResp struct {
	Id         int64  `json:"id"`
	Account    string `json:"account"`
	NickName   string `json:"nickName"`
	CreateTime string `json:"createTime"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UpdateCustomerReq struct {
	Id       int64  `json:"id"`
	UserName string `json:"username,optional"`
	Industry string `json:"industry,optional"`
}

type UpdateUserReq struct {
	Id       int64  `json:"id"`
	NickName string `json:"nickName"`
}
