CREATE TABLE `customer` (
                            `id` BIGINT ( 20 ) UNSIGNED NOT NULL AUTO_INCREMENT,
                            `created_at` datetime ( 3 ) DEFAULT NULL,
                            `updated_at` datetime ( 3 ) DEFAULT NULL,
                            `user_name` VARCHAR ( 200 ) DEFAULT NULL COMMENT '用户名',
                            `password` LONGTEXT,
                            `creator` LONGTEXT,
                            `updater` LONGTEXT,
                            `status` BIGINT ( 20 ) DEFAULT NULL,
                            `phone` VARCHAR ( 40 ) DEFAULT NULL COMMENT '联系方式',
                            `appendix` LONGTEXT,
                            `real_name` LONGTEXT,
                            `remark` LONGTEXT COMMENT '备注',
                            `contact` VARCHAR ( 200 ) DEFAULT NULL COMMENT '联系人',
                            `agent_id` BIGINT ( 20 ) UNSIGNED DEFAULT NULL COMMENT '代理商id',
                            `business_ids` LONGTEXT,
                            `housekeeper_id` BIGINT ( 20 ) UNSIGNED DEFAULT NULL COMMENT '管家id',
                            `industry` VARCHAR ( 50 ) DEFAULT NULL COMMENT '行业',
                            `o_fat` date DEFAULT '1970-01-01' COMMENT '巨量首次达标日期',
                            `k_fat` date DEFAULT '1970-01-01' COMMENT '快手首次达标日期',
                            `i_fat` date DEFAULT '1970-01-01' COMMENT '快手首次达标日期',
                            `ratio` DOUBLE DEFAULT '0' COMMENT '服务费率',
                            `commission` BIGINT ( 20 ) DEFAULT '0' COMMENT '是否返佣 1 是 2 否',
                            `u_fat` date DEFAULT '1970-01-01' COMMENT 'uc首次达标日期',
                            `role` TINYINT ( 3 ) UNSIGNED DEFAULT '0' COMMENT '账号角色 0-客户 1-运营',
                            `p_id` BIGINT ( 20 ) UNSIGNED DEFAULT '0' COMMENT '所属父类id',
                            `type` BIGINT ( 20 ) DEFAULT '0' COMMENT '客户类型：1直签,2代理',
                            `subject` VARCHAR ( 191 ) DEFAULT '' COMMENT '合同主体',
                            PRIMARY KEY ( `id` )
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4;
